### ISSUE TITLE
Tag version 1.0.0 of this action

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/install-juliaup#12]
This action now works, and users can already use it by doing:

```yaml
- uses: julia-actions/install-juliaup@latest
  with:
    julia-version: '1'
```

However, in general, we prefer to not recommend that people use `@latest`. So we should make a v1 tag of this action, so that users can instead do:

```yaml
- uses: julia-actions/install-juliaup@v1
  with:
    julia-version: '1'
```
